image: node:8.9.2
clone:
 depth: full

pipelines:
  default:
    - step:
        name: Deploy REST API to Heroku
        deployment: production
        script: 
          - git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git 